[package]
name = "tsp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap-stdin = "0.4"
rand = "0.8"
roaring = "0.10"
rust_decimal = { version = "1", features = ["maths", "rand"] }
rust_decimal_macros = "1"
